return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "typescript",
      "rust",
      "javascript",
      "json",
      "html",
      "css",
      "bash",
      "python",
      "go",
      "c",
      "cpp",
      "java",
      "yaml",
      "toml",
      "regex",
      "comment",
      "query",
      "tsx",
      "hcl",
      "graphql",
      "kotlin",
      "dockerfile",
    },
  },
}
