source-file ~/.config/tmux/tmux.reset.conf
set-option -g terminal-overrides ',xterm-256color:RGB'

# set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'catppuccin/tmux'

set -g @resurrect-strategy-nvim 'session'

# --- Catppuccin Config ---
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Disable tmux's and the shell's ability to rename windows automatically
# This stops the hostname from being forced into the status bar
set-option -g allow-rename off

# Use 'window_text' (NOT default_text) for inactive tabs
set -g @catppuccin_window_text " #{pane_current_command}"
set -g @catppuccin_window_current_text " #{pane_current_command}"

set -g @catppuccin_window_current_background "#{@thm_mauve}"

# Status bar modules
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"

# Load the plugin
run "~/.config/tmux/plugins/tmux/catppuccin.tmux"

# Set lengths
set -g status-left-length 20
set -g status-right-length 30

#Fix Color scheme for k9s
set -g default-terminal "${TERM}"
set -ga terminal-overrides ",alacritty:Tc"

#Bind sessionizer to <leader> f
bind-key -r f run-shell -b "$DOTFILES/sessionizer/session.sh"

#Open opencode in the current directory in a popup window
bind o popup -E -d "#{pane_current_path}" -w 90% -h 90% "opencode"

# always at end of file
run '~/.config/tmux/plugins/tpm/tpm'
