source_if_exists () {
    if test -r "$1"; then
        source "$1"
    fi
}

source_if_exists $HOME/.env.sh
source_if_exists $DOTFILES/zsh/history.zsh
source_if_exists $DOTFILES/zsh/git.zsh
source_if_exists $DOTFILES/zsh/aliases.zsh
source_if_exists /usr/local/etc/profile.d/z.sh
source_if_exists /opt/homebrew/etc/profile.d/z.sh

. "$HOME/.asdf/asdf.sh"

#When Using GO with ASDF this must be present
. ${ASDF_DATA_DIR:-$HOME/.asdf}/plugins/golang/set-env.zsh

if type "direnv" > /dev/null; then
    eval "$(direnv hook zsh)"
fi

#Open Buffer line in Editor
#Press Control+x, Control+e
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# Enable Vim Style Command Editing
bindkey -v

#Enable zmv for moving files
autoload -U zmv

autoload -U promptinit && promptinit
autoload -U colors && colors
autoload -Uz compinit && compinit

if test -z ${ZSH_HIGHLIGHT_DIR+x}; then
else
    source $ZSH_HIGHLIGHT_DIR/zsh-syntax-highlighting.zsh
fi

precmd() {
    source $DOTFILES/zsh/aliases.zsh
}

export VISUAL=nvim
export EDITOR=nvim
export PATH="$PATH:/usr/local/sbin:$DOTFILES/bin:$HOME/.local/bin:$DOTFILES/scripts/"

# Load Starship
eval "$(starship init zsh)"

# ZSH Autosuggestions
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# ZSH Syntax Highlighting
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh  

#Load Zoxide
eval "$(zoxide init zsh)"

#Source SDKMAN
source "$HOME/.sdkman/bin/sdkman-init.sh"


# Needs to be loaded toward the end
source_if_exists ~/.fzf.zsh
source <(fzf --zsh)

#Atuin Better history search
. "$HOME/.atuin/bin/env"

eval "$(atuin init zsh --disable-up-arrow)"

#JJ Autocompletions
source <(COMPLETE=zsh jj)

# Autogenerated by pnpm
# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="$HOME/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

#
fpath=(~/.stripe $fpath)
autoload -Uz compinit && compinit -i
